version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./week1/sakila-mysql.sql:/docker-entrypoint-initdb.d/sakila-mysql.sql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge
