server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: week3-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: week3
          __path__: /var/log/week3/*.log
    pipeline_stages:
      - match:
          selector: '{job="week3"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\S+) (?P<level>\S+) (?P<thread>\S+) (?P<logger>\S+) (?P<message>.*)'
            - timestamp:
                source: timestamp
                format: '2006-01-02 15:04:05'
            - labels:
                level:
                thread:
                logger:
