spring.application.name=grpc

# gRPC Server Configuration (net.devh)
grpc.server.port=9090
grpc.server.address=0.0.0.0

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Disable H2 Console (since no web server)
spring.h2.console.enabled=false
